apiVersion: v1
kind: Pod
metadata:
  name: hello-world-repeated
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello world; sleep 10;done"]
  restartPolicy: OnFailure
